-- Supabase schema split into ordered parts.
-- Run these files in order:
-- 1. supabase/schema/01-extensions-auth.sql
-- 2. supabase/schema/02-tables.sql
-- 3. supabase/schema/03-rls-policies.sql
-- 4. supabase/schema/04-indexes.sql
