
import "../styles/index.scss"
// import type { Metadata } from 'next'

// export const metadata: Metadata = {
//   title: 'MediDove React Next js Tempalte',
//   description: 'Generated by create next app',
// }

// https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700|Rubik:400,500,700

// import { Poppins, Rubik} from "next/font/google";
// const poppins = Poppins({
//   weight: ["200","300","400", "500", "600", "700"],
//   subsets: ["latin"], 
//   variable:  "--tp-ff-charm",
// });
// const rubik = Rubik({
//   weight: [ "400","500", "700"],
//   subsets: ["latin"], 
//   variable:  "--"
// });

 



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.ico" sizes="any" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700|Rubik:400,500,700"
        />
      </head>
      <body >{children}</body>
    </html>
  )
}
