create index departments_slug_idx on public.departments(slug);
create index staff_members_profile_id_idx on public.staff_members(profile_id);
create index staff_members_role_status_idx on public.staff_members(role, status);
create index doctors_slug_idx on public.doctors(slug);
create index doctors_profile_id_idx on public.doctors(profile_id);
create index doctors_department_id_idx on public.doctors(department_id);
create index doctor_availability_doctor_id_idx on public.doctor_availability(doctor_id);
create index doctor_availability_weekday_idx on public.doctor_availability(weekday);
create index services_slug_idx on public.services(slug);
create index services_department_id_idx on public.services(department_id);
create index health_packages_slug_idx on public.health_packages(slug);
create index health_packages_active_idx on public.health_packages(is_active, is_featured);
create index products_slug_idx on public.products(slug);
create index products_active_idx on public.products(is_active, is_featured);
create index products_category_idx on public.products(category);
create index testimonials_published_idx on public.testimonials(is_published, is_featured);
create index blog_posts_slug_idx on public.blog_posts(slug);
create index blog_posts_published_idx on public.blog_posts(is_published, published_at desc);
create index appointments_status_idx on public.appointments(status);
create index appointments_requested_at_idx on public.appointments(requested_at);
create index clinical_notes_patient_id_idx on public.clinical_notes(patient_id);
create index clinical_notes_appointment_id_idx on public.clinical_notes(appointment_id);
create index clinical_notes_created_at_idx on public.clinical_notes(created_at desc);
create index contact_leads_ai_urgency_idx on public.contact_leads(ai_urgency);
create index patient_feedback_status_idx on public.patient_feedback(status);
create index patient_feedback_sentiment_idx on public.patient_feedback(ai_sentiment);
create index patient_feedback_created_at_idx on public.patient_feedback(created_at desc);
create index care_tasks_status_idx on public.care_tasks(status);
create index care_tasks_priority_idx on public.care_tasks(priority);
create index care_tasks_due_at_idx on public.care_tasks(due_at);
create index care_tasks_assigned_to_idx on public.care_tasks(assigned_to);
create index call_logs_status_idx on public.call_logs(status);
create index whatsapp_messages_status_idx on public.whatsapp_messages(status);
create index consent_logs_channel_idx on public.consent_logs(channel);
create index consent_logs_patient_channel_idx on public.consent_logs(patient_id, channel, created_at desc);
create index consent_logs_phone_channel_idx on public.consent_logs(phone, channel, created_at desc);
create index consent_logs_email_channel_idx on public.consent_logs(email, channel, created_at desc);
create index opt_outs_patient_channel_idx on public.opt_outs(patient_id, channel, created_at desc);
create index opt_outs_phone_channel_idx on public.opt_outs(phone, channel, created_at desc);
create index opt_outs_email_channel_idx on public.opt_outs(email, channel, created_at desc);
create index message_templates_channel_idx on public.message_templates(channel);
create index message_templates_category_idx on public.message_templates(category);
create index communication_outbox_channel_idx on public.communication_outbox(channel);
create index communication_outbox_status_idx on public.communication_outbox(status);
create index automation_rules_trigger_event_idx on public.automation_rules(trigger_event);
create index automation_rules_active_idx on public.automation_rules(is_active);
create index campaigns_status_idx on public.campaigns(status);
create index campaigns_channel_idx on public.campaigns(channel);
create index campaign_recipients_campaign_id_idx on public.campaign_recipients(campaign_id);
create index campaign_recipients_status_idx on public.campaign_recipients(status);
create index audit_logs_event_type_idx on public.audit_logs(event_type);
create index audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index ai_chat_messages_session_id_idx on public.ai_chat_messages(session_id);
create index ai_leads_status_idx on public.ai_leads(status);
create index ai_leads_session_id_idx on public.ai_leads(session_id);
create index ai_leads_created_at_idx on public.ai_leads(created_at desc);
create index ai_document_chunks_embedding_idx
  on public.ai_document_chunks
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);
